[toolchain]
# Defines the Rust toolchain for the project (optional)

[features]
resolution = true
skip-lint = false

[programs.localnet]
# The program ID matches the one used in your tests and deployment
middle_earth_ai_program = "FE7WJhRY55XjHcR22ryA3tHLq6fkDNgZBpbh25tto67Q"

[registry]
# The Anchor registry URL (optional for localnet)
url = "https://anchor.projectserum.com"

[provider]
# Configuration for the local Solana cluster and wallet
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# Script for running TypeScript-based tests
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
